target("FlexCommon")
    set_kind("static")
    add_files("src/**.cpp", "src/**.c")
    add_headerfiles("include/**")
    add_includedirs("include", { public = true })
    add_includedirs("src")
    set_languages("cxx20")

    add_deps("asio", { public = true })
target_end()